[package]
name = "swiss_knife"
version = "0.1.0"
edition = "2018"

[dependencies]
qmetaobject = "0.2.2"
log = "0.4.11"
log4rs = {version = "1.0.0", features = ["gzip"]}
json = "*"
urlencoding = "*"

[[example]]
name = "showcase"
path = "examples/showcase.rs"
